### ISSUE TITLE
Boolean Type Clarification

### ISSUE THREAD

**Issue by aloisbarreras** [enquirer/prompt-base#11]
Working on the dev branch, I ran the boolean example `node examples/boolean.js` which presents me with the following prompt.

<img width="509" alt="screen shot 2018-07-05 at 10 21 54 am" src="https://user-images.githubusercontent.com/15008940/42328858-54ea34a8-803d-11e8-861b-a68361f0a765.png">

As a new user, my first inclination was that I would be able use the arrow keys to move up/down and alternate between true and false. However, it initially seemed that no matter what key I pressed, the value would switch to false and it would be stuck there.

I couldn't figure out how to get it back to true, so I thought there might be a bug. I dug into the code, and I found that every keypress is run through this function:

```javascript
cast(val) {
  return /^[ty1]/i.test(val);
}
```

The return value of that function is set as the new value of the prompt. So, with the boolean prompt, you have to hit either "t", "y", or "1" to set the value to true and every other keypress will be false.

I just wanted to bring this up with you guys and let you know that this was pretty confusing for a new user. I was looking at some other prompts and the [prompt-confirm](https://github.com/enquirer/prompt-confirm) package is the interface I would expect for a boolean type.

Some options I'm thinking for making this easier for newcomers:
- Just add a help message to all boolean type prompts that says "Press y, t, or 1 for true" (Not my favorite one)
- The prompt-confirm package becomes the new boolean type. I personally like the [Y/n] interface. It's very familiar from working with linux and other cli tools.
- The boolean type becomes a prompt-choices with default list of values of true/false and you can only select one. This would allow you to use the arrow keys and other standard navigation options and give a visual of the available choices. This seems the most intuitive to me.

Let me know what you guys think!

**Comment by doowb** [comment]
The `types` provided in `prompt-base` are intended to be base level prompts that are inherited to build other prompts. They provide some common functionality that's useful for a certain "type" of prompt. `boolean`, for instance, has the functionality to handle "truthy" and "falsey" values, but it doesn't handle arrow keys because the functionality that occurs when hitting an arrow key is determined by the current value. (e.g. pressing "right arrow" when true, will select false, but when false, will select true).

In the [dev branch of enquirer](https://github.com/enquirer/enquirer/tree/dev/prompts), there are implementations of `prompt-confirm` and `prompt-toggle` which use the boolean type. `prompt-confirm` changes the UI to show `Y/n` as you pointed out, and `prompt-toggle` provides additional keypress functionality to handle toggling the value when pressing arrow keys.

If we decide that the arrow key toggling functionality is common enough to include in `prompt-confirm`, then we could consider moving it to the boolean type. Or, as you mentioned linux and other cli tools... if the right arrow always selects the "falsey" value and the left arrow always selects the "truthy" value, then it might be good to have those in the boolean type, then `prompt-confirm` will gain that feature.

I hope this clears it up.

**Comment by aloisbarreras** [comment]
Yes that makes total sense, thanks!
